# Dependencies
lombokVersion=1.18.36
jspecifyVersion=1.0.0
javalinVersion=7.2.2
jacksonVersion=2.22.1
slf4jVersion=2.0.17

sqliteJdbcVersion=3.45.1.0

junitVersion=6.0.0
mockitoVersion=5.6.0
okhttpVersion=4.12.0
assertjVersion=3.24.2

# Gradle
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.configuration-cache.max-problems=0